// Code generated by hertz generator.

package main

import (
	"tCloudMusic_api/biz/handler/login"

	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	v1 := r.Group("/v1")
	{
		userGroup := v1.Group("/user")
		lgHandler := login.NewLoginHandler()
		userGroup.POST("/login", lgHandler.Login)
		userGroup.POST("/logout", lgHandler.Logout)
	}

	// your code ...
}
